accelerator: null
accumulate_grad_batches: 1
adam_epsilon: 1.0e-09
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: true
batch_size: 10
benchmark: false
bert_path: ../roberta-base/
check_val_every_n_epoch: 1
checkpoint_callback: true
checkpoint_path: ../checkpoint/epoch=4-valid_loss=-0.6472-valid_acc_end=0.9173.ckpt
data_dir: ../multinli_1.0_all
default_root_dir: null
deterministic: false
distributed_backend: null
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 0,1,2,3
gradient_clip_val: 0
lamb: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 2.0e-05
max_epochs: 1000
max_length: 512
max_steps: null
min_epochs: 1
min_steps: null
mode: eval
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: 1
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
save_path: ../save_mnli/
save_topk: 5
span_topk: 5
sync_batchnorm: false
task: mnli
terminate_on_nan: false
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse_utils._gpus_arg_default ''
track_grad_norm: -1
truncated_bptt_steps: null
use_memory: false
val_check_interval: 1.0
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
weights_summary: top
workers: 0
